# config file version
apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Alertmanager
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  version: 1
  editable: false
