global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: bitcoind_exporter
    scheme: http
    static_configs:
      - targets:
          - bitcoind_exporter:8064
