global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: bitcoind_exporter
    scheme: http
    static_configs:
      - targets:
          - bitcoind_exporter:8064
