{
 "title": "Bitcoind",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(getblockchaininfo_blocks{}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoind_uptime{instance=\"$instance\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "bestblock_height{instance=\"$instance\"}",
     "legendFormat": "Best block height"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "targets": [
    {
     "expr": "bestblock_time{instance=\"$instance\"} * 1000",
     "legendFormat": "Best block"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "bestblock_time{instance=\"$instance\"} * 1000",
     "legendFormat": "From now"
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Verification progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "getblockchaininfo_verificationprogress{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Blocks count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "getblockchaininfo_blocks{instance=\"$instance\"}",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Headers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "getblockchaininfo_headers{instance=\"$instance\"}",
     "legendFormat": "headers"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "getblockchaininfo_difficulty{instance=\"$instance\"}",
     "legendFormat": "Diff"
    }
   ]
  },
  {
   "title": "Median time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "getblockchaininfo_mediantime{instance=\"$instance\"}",
     "legendFormat": "Median time"
    }
   ]
  },
  {
   "title": "Best block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "bestblock_size{instance=\"$instance\"}",
       "legendFormat": "Size"
      },
      {
       "expr": "bestblock_strippedsize{instance=\"$instance\"}",
       "legendFormat": "StrippedSize"
      }
     ]
    },
    {
     "title": "Difficulty",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bestblock_difficulty{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bestblock_time{instance=\"$instance\"} * 1000"
      }
     ]
    },
    {
     "title": "Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bestblock_tx_count{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mempool tx count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "getmempoolinfo_size{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Mempool size in bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "getmempoolinfo_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Total memory usage for the mempool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "getmempoolinfo_usage{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Maximum memory usage for the mempool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 13, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "getmempoolinfo_maxmempool{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Minimum fee rate in BTC/kB for tx to be accepted.",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "BTC/kB" } },
     "targets": [
      {
       "expr": "getmempoolinfo_mempoolminfee{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mining info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "The current block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "getmininginfo_blocks{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "The block weight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 11 },
     "targets": [
      {
       "expr": "getmininginfo_currentblockweight{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "The number of block transactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 6, "y": 11 },
     "targets": [
      {
       "expr": "getmininginfo_currentblocktx{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "The current difficulty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 10, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "getmininginfo_difficulty{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "The network hashes per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "Hs" } },
     "yaxes": [
      { "format": "Hs" }
     ],
     "targets": [
      {
       "expr": "getmininginfo_networkhashps{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "The size of the mempool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 11 },
     "targets": [
      {
       "expr": "getmininginfo_pooledtx{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fees",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated fee rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "BTC/kB" } },
     "targets": [
      {
       "expr": "estimatesmartfee_feerate{instance=\"$instance\"}",
       "legendFormat": "{{ conf_target }} / {{ estimate_mode }}"
      }
     ]
    },
    {
     "title": "Short feerate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "BTC/kB" } },
     "targets": [
      {
       "expr": "estimaterawfee_short_feerate{instance=\"$instance\"}",
       "legendFormat": "{{ conf_target }} / {{ threshold }}"
      }
     ]
    },
    {
     "title": "Medium feerate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "BTC/kB" } },
     "targets": [
      {
       "expr": "estimaterawfee_medium_feerate{instance=\"$instance\"}",
       "legendFormat": "{{ conf_target }} / {{ threshold }}"
      }
     ]
    },
    {
     "title": "Long feerate",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "BTC/kB" } },
     "targets": [
      {
       "expr": "estimaterawfee_long_feerate{instance=\"$instance\"}",
       "legendFormat": "{{ conf_target }} / {{ threshold }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "getmemoryinfo_total{instance=\"$instance\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "getmemoryinfo_used{instance=\"$instance\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "getmemoryinfo_free{instance=\"$instance\"}",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Memory locked",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "getmemoryinfo_locked{instance=\"$instance\"}",
       "legendFormat": "Locked"
      }
     ]
    },
    {
     "title": "Memory chunks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "getmemoryinfo_chunks_free{instance=\"$instance\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "getmemoryinfo_chunks_used{instance=\"$instance\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(getnettotals_totalbytesrecv{instance=\"$instance\"}[5m])",
       "legendFormat": "Received"
      },
      {
       "expr": "-rate(getnettotals_totalbytessent{instance=\"$instance\"}[5m])",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Network info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server version",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "getnetworkinfo_version" }
     ]
    },
    {
     "title": "Protocol version",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 2, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "getnetworkinfo_protocolversion" }
     ]
    },
    {
     "title": "Time offset",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 3, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "getnetworkinfo_timeoffset", "legendFormat": "Offset" }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 3, "x": 7, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "getnetworkinfo_connections" }
     ]
    },
    {
     "title": "Connections In/Out",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 3, "x": 10, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "getnetworkinfo_connections_in", "legendFormat": "In" },
      {
       "expr": "getnetworkinfo_connections_out * -1",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Is network active",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 13, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "getnetworkinfo_networkactive" }
     ]
    },
    {
     "title": "Relay fee",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "BTC/kB" } },
     "targets": [
      { "expr": "getnetworkinfo_relayfee" }
     ]
    },
    {
     "title": "minimum fee increment",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "BTC/kB" } },
     "targets": [
      { "expr": "getnetworkinfo_incrementalfee" }
     ]
    }
   ]
  }
 ]
}